CREATE DATABASE ShopOline
-- SẢN PHẨM
CREATE TABLE SANPHAM (
	MASP VARCHAR(3) NOT NULL,
	TENSP NVARCHAR(50) NOT NULL,
	GIA MONEY NOT NULL,
	TINHTRANG NVARCHAR(20) NOT NULL,
	MOTA NVARCHAR(3000),
	HINHCHINH NVARCHAR(10),
	MALOAI VARCHAR(3) NOT NULL,
	CONSTRAINT PK_MSP PRIMARY KEY (MASP)
	)

-- LOẠI SẢN PHẨM
CREATE TABLE LOAISP (
	MALOAI VARCHAR(3) NOT NULL,
	TENLOAI NVARCHAR(50) NOT NULL,
	TINHTRANG NVARCHAR(20) NOT NULL,
	CONSTRAINT PK_LSP PRIMARY KEY (MALOAI)
	)

-- THÀNH VIÊN
CREATE TABLE THANHVIEN (
	MATHANHVIEN VARCHAR(20),
	TENTHANHVIEN NVARCHAR(30) NOT NULL,
	DIACHI NVARCHAR (100) NOT NULL,
	GIOITINH NVARCHAR(3) CHECK (GIOITINH IN(N'NAM',N'nữ')),
	SODIENTHOAI CHAR(10) NOT NULL CHECK (LEN(SODIENTHOAI) =10)
	CONSTRAINT PK_TV PRIMARY KEY (MATHANHVIEN)
	)

-- TÀI KHOẢN THÀNH VIÊN
CREATE TABLE TAIKHOANTHANHVIEN (
	MATAIKHOAN VARCHAR(20),
	MATHANHVIEN VARCHAR(20) NOT NULL,
	TENDANGNHAP VARCHAR(50) NOT NULL,
	MATKHAU VARCHAR(50) NOT NULL,
	CONSTRAINT PK_TKTV PRIMARY KEY (MATAIKHOAN)
	)

-- GIỎ HÀNG
CREATE TABLE GIOHANG (
	MAGIOHANG VARCHAR(20),
	NGAYTHEM DATE,
	CONSTRAINT PK_GH PRIMARY KEY (MAGIOHANG)
	)

-- CHI TIẾT GIỎ HÀNG
CREATE TABLE CHITIETGIOHANG (
	MAGIOHANG VARCHAR(20),
	MASP VARCHAR(3),
	SOLUONG INT NOT NULL CHECK (SOLUONG >0),
	CONSTRAINT PK_MGH PRIMARY KEY (MAGIOHANG, MASP)
	)

-- ĐƠN HÀNG
CREATE TABLE DONHANG (
	MADONHANG VARCHAR(20) NOT NULL,
	TRIGIA MONEY NOT NULL,
	NGAYDONHANG DATE NOT NULL,
	PHUONGTHUCTHANHTOAN NVARCHAR(30) NOT NULL,
	MATHANHVIEN VARCHAR(20) NOT NULL,
	MATAIKHOAN VARCHAR(20) NOT NULL,
	CONSTRAINT PK_DH PRIMARY KEY (MADONHANG)
	)

-- CHI TIẾT ĐƠN HÀNG
CREATE TABLE CHITIETDONHANG (
	MADONHANG VARCHAR(20),
	MASP VARCHAR(3),
	SOLUONG INT NOT NULL CHECK (SOLUONG >0),
	CONSTRAINT PK_CTDH PRIMARY KEY (MADONHANG, MASP)
	)

-- ĐÁNH GIÁ
CREATE TABLE DANHGIA (
	MADANHGIA VARCHAR(20),
	MATHANHVIEN VARCHAR(20),
	MASP VARCHAR(3) NOT NULL,
	NOIDUNG NVARCHAR(200) NOT NULL,
	CONSTRAINT PK_DG PRIMARY KEY (MADANHGIA)
	)

	-- TẠO KHÓA NGOẠI BẢNG SẢN PHẨM
	ALTER TABLE SANPHAM ADD CONSTRAINT FK1_SP FOREIGN KEY (MALOAI) REFERENCES LOAISP (MALOAI)
	-- TẠO KHÓA NGOẠI BẢNG CHI TIẾT GIỎ HÀNG
	ALTER TABLE CHITIETGIOHANG ADD CONSTRAINT FK1_CTGH FOREIGN KEY(MAGIOHANG) REFERENCES GIOHANG(MAGIOHANG)
	ALTER TABLE CHITIETGIOHANG ADD CONSTRAINT FK2_CTGH FOREIGN KEY(MASP) REFERENCES SANPHAM(MASP)
	-- TẠO KHÓA NGOẠI BẢNG ĐƠN HÀNG
	ALTER TABLE DONHANG ADD CONSTRAINT FK1_DH FOREIGN KEY (MATHANHVIEN) REFERENCES THANHVIEN(MATHANHVIEN)
	ALTER TABLE DONHANG ADD CONSTRAINT FK2_DH FOREIGN KEY (MATAIKHOAN) REFERENCES TAIKHOANTHANHVIEN (MATAIKHOAN)
	-- TẠO KHÓA NGOẠI BẢNG CHI TIẾT ĐƠN HÀNG
	ALTER TABLE CHITIETDONHANG ADD CONSTRAINT FK1_CTDH FOREIGN KEY (MADONHANG) REFERENCES DONHANG(MADONHANG)
	ALTER TABLE CHITIETDONHANG ADD CONSTRAINT FK2_CTDH FOREIGN KEY (MASP) REFERENCES SANPHAM(MASP)
	-- TẠO KHÓA NGOẠI BẢNG TÀI KHOẢN THÀNH VIÊN
	ALTER TABLE TAIKHOANTHANHVIEN ADD CONSTRAINT FK1_TKTV FOREIGN KEY (MATHANHVIEN) REFERENCES THANHVIEN(MATHANHVIEN)
	-- TẠO KHÓA NGOẠI BẢNG ĐÁNH GIÁ
	ALTER TABLE DANHGIA ADD CONSTRAINT FK1_DG FOREIGN KEY (MATHANHVIEN) REFERENCES THANHVIEN(MATHANHVIEN)
	ALTER TABLE DANHGIA ADD CONSTRAINT FK2_DG FOREIGN KEY (MASP) REFERENCES SANPHAM(MASP)

	-- CHỈNH FORMAT NGÀY THÀNH DATE-MONTH-YEAR(NGÀY-THÁNG-NĂM)
	SET DATEFORMAT DMY


select * from THANHVIEN
select * from LOAISP
select * from SANPHAM
select * from TAIKHOANTHANHVIEN
select * from DONHANG
select * from CHITIETDONHANG
select * from CHITIETGIOHANG
select * from DANHGIA
select * from GIOHANG

DROP TABLE THANHVIEN
DROP TABLE LOAISP
DROP TABLE SANPHAM
DROP TABLE TAIKHOANTHANHVIEN
DROP TABLE DONHANG
DROP TABLE CHITIETDONHANG
DROP TABLE CHITIETGIOHANG
DROP TABLE DANHGIA
DROP TABLE GIOHANG

--INSERT DU LIEU
-- BANG SANPHAM

INSERT INTO SANPHAM VALUES ('A01','ADIDAS 1', '650.000', N'ĐANG HIỂN THỊ', 'Timeless elegance for your feet','A01.JPG', '001')
INSERT INTO SANPHAM VALUES ('A02','ADIDAS 2', '550.000', N'ĐANG HIỂN THỊ', 'Fuel your stride with comfort','A02.JPG','001')
INSERT INTO SANPHAM VALUES ('A03','ADIDAS 3', '450.000', N'ĐANG HIỂN THỊ', 'Elevate your style effortlessly', 'A03.JPG', '001')
INSERT INTO SANPHAM VALUES ('Y01','YEEZY 1', '650.000', N'ĐANG HIỂN THỊ', 'Timeless elegance for your feet','Y01.JPG', '002')
INSERT INTO SANPHAM VALUES ('Y02','YEEZY 2', '550.000', N'ĐANG HIỂN THỊ', 'Fuel your stride with comfort','Y02.JPG','002')
INSERT INTO SANPHAM VALUES ('Y03','YEEZY 3', '450.000', N'ĐANG HIỂN THỊ', 'Elevate your style effortlessly', 'Y03.JPG', '002')
INSERT INTO SANPHAM VALUES ('J01','JORDAN 1', '650.000', N'ĐANG HIỂN THỊ', 'Timeless elegance for your feet','J01.JPG', '003')
INSERT INTO SANPHAM VALUES ('J02','JORDAN 2', '550.000', N'ĐANG HIỂN THỊ', 'Fuel your stride with comfort','J02.JPG','003')
INSERT INTO SANPHAM VALUES ('J03','JORDAN 3', '450.000', N'ĐANG HIỂN THỊ', 'Elevate your style effortlessly', 'J03.JPG', '003')
INSERT INTO SANPHAM VALUES ('N01','NIKE 1', '650.000', N'ĐANG HIỂN THỊ', 'Timeless elegance for your feet','N01.JPG', '004')
INSERT INTO SANPHAM VALUES ('N02','NIKE 2', '550.000', N'ĐANG HIỂN THỊ', 'Fuel your stride with comfort','N02.JPG','004')
INSERT INTO SANPHAM VALUES ('N03','NIKE 3', '450.000', N'ĐANG HIỂN THỊ', 'Elevate your style effortlessly', 'N03.JPG', '004')
INSERT INTO SANPHAM VALUES ('D01','DREW HOUSE 1', '650.000', N'ĐANG HIỂN THỊ', 'Timeless elegance for your feet','D01.JPG', '005')
INSERT INTO SANPHAM VALUES ('D02','DREW HOUSE 2', '550.000', N'ĐANG HIỂN THỊ', 'Fuel your stride with comfort','D02.JPG','005')
INSERT INTO SANPHAM VALUES ('D03','DREW HOUSE 3', '450.000', N'ĐANG HIỂN THỊ', 'Elevate your style effortlessly', 'D03.JPG', '005')


-- BANG LOAISANPHAM
INSERT INTO LOAISP VALUES ('001', 'ADIDAS', N'ĐANG HIỂN THỊ')
INSERT INTO LOAISP VALUES ('002', 'YEEZY', N'ĐANG HIỂN THỊ')
INSERT INTO LOAISP VALUES ('003', 'JORDAN', N'ĐANG HIỂN THỊ')
INSERT INTO LOAISP VALUES ('004', 'NIKE', N'ĐANG HIỂN THỊ')
INSERT INTO LOAISP VALUES ('005', 'DREW HOUSE', N'ĐANG HIỂN THỊ')
INSERT INTO LOAISP VALUES ('006', 'NO NAME', N'ẨN')

-- BANG THANHVIEN
INSERT INTO THANHVIEN VALUES ('LT001', N'NGUYỄN TRẦN TRUNG QUÂN', N'MỸ THO', N'NAM', '0901235895')
INSERT INTO THANHVIEN VALUES ('LT002', N'TRẦN THIỆN THANH BẢO', N'HỒ CHÍ MINH', N'NAM', '0901235875')
INSERT INTO THANHVIEN VALUES ('LT003', N'NGUYỄN THANH TÙNG', N'GIA LAI', N'NAM', '0901455895')
INSERT INTO THANHVIEN VALUES ('LT004', N'LÊ NGUYỄN TRUNG ĐAN', N'MỸTHO', N'NAM', '0901278895')
INSERT INTO THANHVIEN VALUES ('LT005', N'PHẠM HOÀNG KHOA', N'BẾN TRE', N'NAM', '0901234595')
INSERT INTO THANHVIEN VALUES ('LT006', N'HÀNG LÂM TRANG ANH', N'THÁI BÌNH', N'NỮ', '0341235895')
INSERT INTO THANHVIEN VALUES ('LT007', N'NGUYỄN THÙY CHI', N'HÀ NỘI', N'NỮ', '0902465895')
INSERT INTO THANHVIEN VALUES ('LT008', N'ĐẶNG THU THẢO', N'TÂY NINH', N'NỮ', '0901239995')
INSERT INTO THANHVIEN VALUES ('LT009', N'THẢO TRỊNH', N'MỸTHO', N'NỮ', '0998535895')
INSERT INTO THANHVIEN VALUES ('LT010', N'NGUYỄN ĐỨC CƯỜNG', N'BÌNH ĐỊNH', N'NAM', '0974135895')


























----BANG SAN PHAM
--CREATE TABLE SANPHAM (
--MASP VARCHAR(3) NOT NULL,
--MALOAI VARCHAR(5) NOT NULL,
--MANSX CHAR(9) NOT NULL,
--TENSP NVARCHAR(40),
--MOTA NVARCHAR(20),
--HINHCHINH CHAR(9),
--HINHPHU CHAR(9),
--GIA MONEY,
--SOLUONGDABAN INT,
--LUOTVIEW INT,
--TINHTRANG CHAR(9) DEFAULT '0',
--GHIGHU NVARCHAR(50) DEFAULT 'NEW'
--CONSTRAINT PK_SP PRIMARY KEY (MASP)
--)

--sp_rename 'SANPHAM.HINHCHINH', 'MAHINHANH', 'COLUMN';

--DROP TABLE SANPHAM

----BANG NHA SAN XUAT
--CREATE TABLE NHASANXUAT (
--MANSX CHAR(9) NOT NULL,
--TENNSX NVARCHAR(40),
--TINHTRANG NVARCHAR(3) DEFAULT '0'
--CONSTRAINT PK_NHASANXUAT PRIMARY KEY (MANSX)
--)
--DROP TABLE NHASANXUAT

----BANG LOAI SAN PHAM
--CREATE TABLE LOAISP (
--MALOAI VARCHAR(5),
--TENLOAI NVARCHAR(40),
--TINHTRANG NVARCHAR(3) DEFAULT '0'
--CONSTRAINT PK_LOAISP PRIMARY KEY (MALOAI)
--)
--DROP TABLE LOAISP

----KHOA NGOAI
--ALTER TABLE SANPHAM ADD CONSTRAINT FK1_SP FOREIGN KEY(MALOAI) REFERENCES LOAISP(MALOAI)
--ALTER TABLE SANPHAM ADD CONSTRAINT FK2_SP FOREIGN KEY(MANSX) REFERENCES NHASANXUAT(MANSX)


----INSERT DU LIEU
----BANG SANPHAM
--INSERT INTO SANPHAM VALUES ('S01','ADD','TQ','SNEAKER',N'SANG CHẢNH', 'S01.JPG', 'SS01.JPG', '270000','5','120','0','NEW')
--INSERT INTO SANPHAM VALUES ('S02','ADD','TQ','SNEAKER',N'SANG CHẢNH', 'S02.JPG', 'SS02.JPG', '230000','5','120','0','NEW')
--INSERT INTO SANPHAM VALUES ('S03','YZ','VN','SNEAKER',N'SANG CHẢNH, HỢP GU', 'S03.JPG', 'SS03.JPG', '280000','5','120','0','NEW')
--INSERT INTO SANPHAM VALUES ('A01','JD','TQ','ADIDAS',N'ĐẲNG CẤP, THƯỢNG LƯU', 'A01.JPG', 'AA01.JPG', '370000','5','120','0','NEW')
--INSERT INTO SANPHAM VALUES ('A02','C$SF','MY','ADIDAS',N'ĐẲNG CẤP, THƯỢNG LƯU', 'A02.JPG', 'AA02.JPG', '220000','5','120','0', 'NEW')
--INSERT INTO SANPHAM VALUES ('A02','DRH','MY','CONVERT',N'ĐẲNG CẤP, THƯỢNG LƯU', 'A02.JPG', 'AA02.JPG', '220000','5','120','0', 'NEW')

----BANG LOAISANPHAM
--INSERT INTO LOAISP VALUES ('ADD', 'ADIDAS', '0')
--INSERT INTO LOAISP VALUES ('YZ', 'YEEZY', '0')
--INSERT INTO LOAISP VALUES ('JD', 'JORDAN', '0')
--INSERT INTO LOAISP VALUES ('CASF', 'CAT & SOFA', '0')
--INSERT INTO LOAISP VALUES ('DRH', 'DREW HOUSE', '0')

----BANG NHA SAN XUAT
--INSERT INTO NHASANXUAT VALUES ('TQ', N'TRUNG QUỐC','0')
--INSERT INTO NHASANXUAT VALUES ('VN', N'VIỆT NAM','0')
--INSERT INTO NHASANXUAT VALUES ('MY', N'MỸ','0')

--SELECT * FROM SANPHAM
--SELECT * FROM NHASANXUAT
--SELECT * FROM LOAISP


